# Generated by Django 4.0.4 on 2022-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('firstName', models.CharField(blank=True, max_length=15, null=True, verbose_name='名')),
                ('lastName', models.CharField(blank=True, max_length=15, null=True, verbose_name='姓')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='メールアドレス')),
                ('introduction', models.TextField(blank=True, max_length=300, null=True, verbose_name='自己紹介')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
