# Generated by Django 4.0.4 on 2022-06-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostingApp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
