# Generated by Django 4.0.4 on 2022-06-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostingApp', '0003_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
