# Generated by Django 4.0.4 on 2022-06-21 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostingApp', '0004_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='related_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
