# Generated by Django 4.0.4 on 2022-06-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostingApp', '0007_rename_user_id_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_id',
        ),
    ]
