# Generated by Django 4.0.4 on 2022-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostingApp', '0009_alter_follow_following_alter_follow_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
